### ISSUE TITLE
flutter build fail

### ISSUE THREAD

**Issue by xj728** [bravekingzhang/dalipush#2]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build apk

## exception

FormatException: FormatException: Bad UTF-8 encoding 0xb4 (at offset 74)

```
#0      _Utf8Decoder.convert (dart:convert/utf.dart:518:13)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:311:14)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#5      _rootRunUnary (dart:async/zone.dart:1132:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#10     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#11     _StreamController._add (dart:async/stream_controller.dart:640:7)
#12     _StreamController.add (dart:async/stream_controller.dart:586:5)
#13     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1774:41)
#14     _rootRunUnary (dart:async/zone.dart:1136:13)
#15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#19     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#20     _StreamController._add (dart:async/stream_controller.dart:640:7)
#21     _StreamController.add (dart:async/stream_controller.dart:586:5)
#22     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1323:33)
#23     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:844:14)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#26     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel dev, v1.2.0, on Microsoft Windows [Version 10.0.17763.253], locale zh-CN)
    [32m•[39m Flutter version 1.2.0 at D:\flutter
    [32m•[39m Framework revision 06b979c4d5 (9 days ago), 2019-01-25 14:27:35 -0500
    [32m•[39m Engine revision 36acd02c94
    [32m•[39m Dart version 2.1.1 (build 2.1.1-dev.3.2 f4afaee422)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at D:\Android\Sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m ANDROID_HOME = D:\Android\Sdk
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Android Studio (version 3.3)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin version 31.3.3
    [32m•[39m Dart plugin version 182.5124
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[32m[✓][39m VS Code (version 1.30.2)
    [32m•[39m VS Code at C:\Users\xujian\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 2.22.3

[33m[!][39m Connected device
    [33m![39m No devices available

[33m![39m Doctor found issues in 1 category.
```

**Comment by bravekingzhang** [comment]
换稳定分支试试，看起来问题和库没多大关系
